"""Initial migration

Revision ID: 98c40ddc8b13
Revises: 
Create Date: 2025-07-10 15:31:30.981957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98c40ddc8b13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_ace_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('service_error_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('serve_success_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('perfect_pass_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('good_pass_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('poor_pass_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('reception_error_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('assist_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('ball_handling_error_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('attack_kill_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('attack_error_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('hitting_efficiency', sa.DECIMAL(precision=5, scale=3), nullable=False),
    sa.Column('first_ball_kill_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('dig_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('block_kill_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('controlled_block_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('blocking_error_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_statistics_id'), 'team_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_team_statistics_name'), 'team_statistics', ['name'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('num_points', sa.Integer(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('enable_momentum', sa.Boolean(), nullable=False),
    sa.Column('team_a_wins', sa.Integer(), nullable=True),
    sa.Column('team_b_wins', sa.Integer(), nullable=True),
    sa.Column('team_a_win_probability', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('team_b_win_probability', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('simulation_time_seconds', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_a_id'], ['team_statistics.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['team_statistics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_table('importance_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('statistic_name', sa.String(length=255), nullable=False),
    sa.Column('feature_category', sa.String(length=100), nullable=False),
    sa.Column('importance_score', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('marginal_impact', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('confidence_interval_lower', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('confidence_interval_upper', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('analysis_config', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importance_analyses_id'), 'importance_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_importance_analyses_simulation_id'), 'importance_analyses', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_importance_analyses_statistic_name'), 'importance_analyses', ['statistic_name'], unique=False)
    op.create_table('simulation_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('winner_team', sa.String(length=1), nullable=False),
    sa.Column('serving_team', sa.String(length=1), nullable=False),
    sa.Column('rally_states', sa.Text(), nullable=False),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('rally_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_points_id'), 'simulation_points', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_points_simulation_id'), 'simulation_points', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_points_simulation_id'), table_name='simulation_points')
    op.drop_index(op.f('ix_simulation_points_id'), table_name='simulation_points')
    op.drop_table('simulation_points')
    op.drop_index(op.f('ix_importance_analyses_statistic_name'), table_name='importance_analyses')
    op.drop_index(op.f('ix_importance_analyses_simulation_id'), table_name='importance_analyses')
    op.drop_index(op.f('ix_importance_analyses_id'), table_name='importance_analyses')
    op.drop_table('importance_analyses')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_team_statistics_name'), table_name='team_statistics')
    op.drop_index(op.f('ix_team_statistics_id'), table_name='team_statistics')
    op.drop_table('team_statistics')
    # ### end Alembic commands ###
